### ISSUE TITLE
Pico Triggers - Legacy Triggers not firing, buttons not selectable

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-radiora2#54] opened 2022-06-12 14:58 UTC
As described in the Indigo Forums, I am not able to select my Pico button in my triggers that existed previously.

Log when editing a trigger to select the button:

```
Lutron RRA2/Caséta Debug        pickButton, typeId = keypadButtonPress, targetId = 1568425632, valuesDict = UiValuesDict : (dict)
     buttonID : 1140550816 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        pickButton, retList = []
   Lutron RRA2/Caséta Debug        roomListGenerator, typeId = keypadButtonPress, targetId = 1568425632, valuesDict = UiValuesDict : (dict)
     buttonID : 1140550816 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        roomListGenerator adding: Unknown Unknown
   Lutron RRA2/Caséta Debug        get_gateway_list: typeId = keypadButtonPress, targetId = 1568425632, valuesDict = UiValuesDict : (dict)
     buttonID : 1140550816 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
```

Log when editing a Pico Button Device:

```
   Lutron RRA2/Caséta Debug        get_gateway_list: typeId = ra2Pico, targetId = 271169010, valuesDict = UiValuesDict : (dict)
     address : 125333848:52.2 (string)
     componentID : 2 (string)
     gateway : 125333848 (string)
     integrationID : 52 (string)
     isButton : true (bool)
     notes :  (string)
```

Log when a pico button event is received by the plugin is very long.  I can provide if needed.

**Comment by FlyingDiver** [comment] 2022-06-12 16:13
<img width="638" alt="image" src="https://user-images.githubusercontent.com/72976/173242624-a9cb8e4e-ea70-49e6-9e36-a8c8779ee1bd.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/72976/173242628-8e706c3a-f393-4ce8-8747-bb3d6d170d1d.png">

**Comment by FlyingDiver** [comment] 2022-06-12 16:24
Edit the pico device(s) again, and this time save not cancel.

**Comment by mlamoure** [comment] 2022-06-12 20:56
Sure thing.  Here are the logs.  First edit + save is on the device.  Second is on the trigger.

```
Lutron RRA2/Caséta Debug        New logLevel = 5
   Lutron RRA2/Caséta Debug        get_gateway_list: typeId = ra2Pico, targetId = 271169010, valuesDict = UiValuesDict : (dict)
     address : 125333848:52.2 (string)
     componentID : 2 (string)
     gateway : 125333848 (string)
     integrationID : 52 (string)
     isButton : true (bool)
     notes :  (string)
   Lutron RRA2/Caséta Debug        validateDeviceConfigUi: typeId = ra2Pico, devId = 271169010
   Z-Wave                          received "Basement Office Temperature" sensor update to 78.9 °F
   Z-Wave                          received "Basement Office Humidity" sensor update to 46%
   Z-Wave                          received "Basement Office Luminance" sensor update to 6 lux
   Z-Wave                          received "Basement Office Ultraviolet" sensor update to 0
   Lutron RRA2/Caséta Debug        pickButton, typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID : 1393283211 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        pickButton, retList = []
   Lutron RRA2/Caséta Debug        roomListGenerator, typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID : 1393283211 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        roomListGenerator adding: Unknown Unknown
   Lutron RRA2/Caséta Debug        get_gateway_list: typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID : 1393283211 (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        pickButton, typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID :  (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        pickButton, retList = []
   Lutron RRA2/Caséta Debug        roomListGenerator, typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID :  (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
   Lutron RRA2/Caséta Debug        roomListGenerator adding: Unknown Unknown
   Lutron RRA2/Caséta Debug        get_gateway_list: typeId = keypadButtonPress, targetId = 1799082248, valuesDict = UiValuesDict : (dict)
     buttonID :  (string)
     clicks : 1 (string)
     gateway : 125333848 (string)
     room : Unknown (string)
```

**Comment by FlyingDiver** [comment] 2022-06-12 21:46
I don't understand why the retList is empty.  That means that none of the button devices meet the criteria for the list builder.

Can you do an experiment?  Switch to a new Database, then run the plugin command to create all the Lutron devices again, then try to create a trigger.

**Comment by mlamoure** [comment] 2022-06-12 23:30
Happy to.  Does it matter that I created my devices manually?  I’ve been using the plugin since long before the create script existed.

**Comment by FlyingDiver** [comment] 2022-06-13 00:14
I think maybe there's a property missing from your devices that got added later.  And with some recent changes it's not fixing them automatically.  Let's see what results you get before we go that way.

Oh - on both the old and new databases, do a "Print Device Details to Log".  It's a right click on the device line in the main Indigo window.

**Comment by sullom** [comment] 2022-06-19 21:52
I am having the same issue. If I can help provide any logs let me know.

**Comment by FlyingDiver** [comment] 2022-06-19 21:57
I need the information requested above.

**Comment by sullom** [comment] 2022-06-19 22:03
This is the device details for my current database
Jun 19, 2022 at 6:02:49 PM
   Script                          
```
address : 1058684139:7.2
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : ra2Pico
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 84880913
globalProps : MetaProps : (dict)
     com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
          address : 1058684139:7.2 (string)
          componentID : 2 (string)
          gateway : 1058684139 (string)
          integrationID : 7 (string)
          isButton : true (bool)
          notes :  (string)
          room : Front Foyer (string)
id : 1220399724
lastChanged : 2022-06-19 17:56:32
lastSuccessfulComm : 2022-06-19 17:56:32
ledStates : []
model : Lutron Pico Button
name : Family End Table PICO - Fan on
onState : False
ownerProps : com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
     address : 1058684139:7.2 (string)
     componentID : 2 (string)
     gateway : 1058684139 (string)
     integrationID : 7 (string)
     isButton : true (bool)
     notes :  (string)
     room : Front Foyer (string)
pluginId : com.jimandnoreen.indigoplugin.lutron-radiora2
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : False
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
```

**Comment by sullom** [comment] 2022-06-19 22:25
From a new database

Jun 19, 2022 at 6:24:22 PM
   Embedded script executor host2 started
   Script                          
```
address : 905231348:7.2
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : ra2Pico
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1329060045
globalProps : MetaProps : (dict)
     com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
          ButtonType : Unknown (string)
          address : 905231348:7.2 (string)
          componentID : 2 (string)
          gateway : 905231348 (string)
          integrationID : 7 (string)
          isButton : True (string)
          listType : button (string)
          room : Front Foyer (string)
id : 635377501
lastChanged : 2022-06-19 18:24:02
lastSuccessfulComm : 2022-06-19 18:24:02
ledStates : []
model : Lutron Pico Button
name : Front Foyer - Pico 1 (905231348:7.2)
onState : False
ownerProps : com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
     ButtonType : Unknown (string)
     address : 905231348:7.2 (string)
     componentID : 2 (string)
     gateway : 905231348 (string)
     integrationID : 7 (string)
     isButton : True (string)
     listType : button (string)
     room : Front Foyer (string)
pluginId : com.jimandnoreen.indigoplugin.lutron-radiora2
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None

```

**Comment by FlyingDiver** [comment] 2022-06-19 22:29
Please confirm the plugin version you're using.  And the last version that worked.  If you switch back, does it start working?

**Comment by sullom** [comment] 2022-06-19 22:36
2022.0.4. 
installed 7.4.0
and I get a full list of buttons.

**Comment by FlyingDiver** [comment] 2022-06-19 22:39
Huh.  And does this happen with both types of button press triggers, or just the old style?

I'll try to recreate, but not sure I'll be able to.

**Comment by sullom** [comment] 2022-06-19 22:44
when I triggers like this they work fine. Doing it as Lutron Caseta Event - Button Presses Doesn't work. Is that want you meant. Not sure what the old style was.

<img width="479" alt="HomeAutomation 2022-06-19 18-42-20" src="https://user-images.githubusercontent.com/81993578/174502987-eda9aaac-182f-442f-8287-ecff8ae48589.png">

**Comment by FlyingDiver** [comment] 2022-06-19 22:49
There are two types of button press events - "Button Presses" and "Button MultiPresses".  Do either of those work properly?
<img width="454" alt="Screen Shot 2022-06-19 at 6 48 54 PM" src="https://user-images.githubusercontent.com/72976/174503171-3b415451-f0dc-437d-b269-516b9f10081f.png">
.

**Comment by sullom** [comment] 2022-06-19 22:57
Neither of these two options work.

**Comment by FlyingDiver** [comment] 2022-06-19 23:56
OK, thanks.  Will dig into it this week.

**Comment by sullom** [comment] 2022-06-20 00:59
Thank you. I’ll use the old version for now since it works. 

Steve

On Jun 19, 2022, at 7:57 PM, Joe Keenan ***@***.***> wrote:

﻿
OK, thanks. Will dig into it this week.

**Comment by FlyingDiver** [comment] 2022-06-20 15:57
So far, I'm unable to recreate this issue.  There's something missing about the way the devices were created.

Is your system RRa2 or Caseta?  When you created the new database, did you do it manually or using the auto-create function?

You created a new database just to test this, correct?  If so, please zip it up and attach it to a post here.

**Comment by mlamoure** [comment] 2022-06-20 22:51
I created a new DB and imported devices from the plugin using the integration report.  Sending to you via email.  My other plugins auto created some devices specific to my network I’d prefer to not share with the general internet.

**Comment by FlyingDiver** [comment] 2022-06-20 22:53
Ah.  I always disable all the other plugins when I do that, but that's fine.

So you're using Caseta?  Or Select?

**Comment by mlamoure** [comment] 2022-06-21 00:05
Caseta Bridge Pro for me.

**Comment by mlamoure** [comment] 2022-06-21 00:06
Also, I did not test the triggers on the new database.  Just created the devices, is all. I can test further if requested, was doing it in a hurry.

**Comment by FlyingDiver** [comment] 2022-06-21 00:07
If you get a chance to try the triggers, please do.

**Comment by FlyingDiver** [comment] 2022-06-21 00:46
Well, that's interesting.  I loaded your database on my dev system running plugin 2022.0.4 and I can create triggers no problem.

**Comment by FlyingDiver** [comment] 2022-06-21 00:47
Device details from one of the Pico devices in the new database:
```
address : 1699187638:23.5
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : ra2Pico
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 633860195
globalProps : MetaProps : (dict)
     com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
          ButtonType : Unknown (string)
          address : 1699187638:23.5 (string)
          componentID : 5 (string)
          gateway : 1699187638 (string)
          integrationID : 23 (string)
          isButton : True (string)
          listType : button (string)
          room : Bridge (string)
id : 105366293
lastChanged : 2000-01-01 00:00:00
lastSuccessfulComm : 2000-01-01 00:00:00
ledStates : []
model : Lutron Pico Button
name : Bridge - Mudroom Remote 1 (1699187638:23.5)
onState : False
ownerProps : com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
     ButtonType : Unknown (string)
     address : 1699187638:23.5 (string)
     componentID : 5 (string)
     gateway : 1699187638 (string)
     integrationID : 23 (string)
     isButton : True (string)
     listType : button (string)
     room : Bridge (string)
pluginId : com.jimandnoreen.indigoplugin.lutron-radiora2
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
```

**Comment by FlyingDiver** [comment] 2022-06-21 15:12
At this point, the only way I'm going to be able to address this is to get my hands on a database that actually exhibits the issue.  Which is probably going to be an older database with devices that were created before whatever change prompted the issue.

Either that, or anyone with the problem will need to recreate their devices.

**Comment by mlamoure** [comment] 2022-06-22 10:50
Here are two things I notice when comparing the auto created devices to the devices that I've persisted for several versions:

* In GlobalProps of my legacy devices, there is no GlobalProps field for ButtonType, and listType.  Those properties are in the newly created devices in your print from the comment above.
* Similarly, In ownerProps of my legacy devices, there is no ButtonType, and listType. 

Anything of those observations help?

**Comment by mlamoure** [comment] 2022-06-22 10:51
Full log of the legacy device details:


```
address : 125333848:52.3
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : ra2Pico
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 0
globalProps : MetaProps : (dict)
     com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
          address : 125333848:52.3 (string)
          componentID : 3 (string)
          gateway : 125333848 (string)
          integrationID : 52 (string)
          isButton : true (bool)
          notes :  (string)
id : 146120663
lastChanged : 2022-06-11 09:46:11
lastSuccessfulComm : 2022-06-11 09:46:11
ledStates : []
model : Lutron Pico Button
name : Basement Bar LED Middle Button
onState : False
ownerProps : com.jimandnoreen.indigoplugin.lutron-radiora2 : (dict)
     address : 125333848:52.3 (string)
     componentID : 3 (string)
     gateway : 125333848 (string)
     integrationID : 52 (string)
     isButton : true (bool)
     notes :  (string)
pluginId : com.jimandnoreen.indigoplugin.lutron-radiora2
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
```

**Comment by FlyingDiver** [comment] 2022-06-22 12:30
listType isn't actually used.  I need to check on ButtonType.  Room is also missing, and I thought I had code in there at one point to put in a default value.  So I'll try to check that.

**Comment by FlyingDiver** [comment] 2022-06-22 16:58
Try this pre-release:  https://github.com/FlyingDiver/Indigo-radiora2/releases/tag/2022.0.5

**Comment by mlamoure** [comment] 2022-06-22 17:30
No change for me on that.  Existing triggers are not firing and editing the triggers, the pico buttons are not populating in the drop down.

**Comment by FlyingDiver** [comment] 2022-06-22 17:31
Make sure debug logging is on, restart the plugin, post the log here.

**Comment by FlyingDiver** [comment] 2022-06-22 17:32
And give me another device dump from one of the pico buttons.

**Comment by FlyingDiver** [comment] 2022-06-22 17:38
Oh, Wait.  Is "Unknown" in the room list?  Did you try selecting that?

**Comment by sullom** [comment] 2022-06-22 18:35
Unknown does show up for me but still didn’t help.

**Comment by FlyingDiver** [comment] 2022-06-22 18:46
Still need the log and device dump.

**Comment by FlyingDiver** [comment] 2022-06-22 21:59
Trying another tack.  The problem is that devices created a long time ago don't have a "room" property, which I'm now using to make the pop-up lists manageable.  It may not be bad for a small Caseta install, but my RRA2 install has well over 100 devices, which makes the button and other lists very hard to deal with.  Hence filtering by room assignment.  

The auto-create routines assign rooms based on the Lutron info.  I had attempted to assign default values but it doesn't seem to work.  So..

So this pre-release allows editing the device to properly assign it to a room.  Once that's done, the devices should show up in the trigger lists properly.

https://github.com/FlyingDiver/Indigo-radiora2/releases/tag/2022.0.6

**Comment by sullom** [comment] 2022-06-22 22:04
That fixed it. I upgraded, went to the pico remote and added the room. then it appears on the button presses menu for that room. Than you so much. I'll just go back and add those rooms and should be good going forward.

**Comment by FlyingDiver** [comment] 2022-06-22 22:10
Excellent.  I'll wait for @mlamoure to try it as well, and test for a few days before I push the release.

**Comment by mlamoure** [comment] 2022-06-22 23:05
Yep, looking good.  I had to open existing triggers and choose the Pico Button, but once they populated and once I did that, all is back to normal.  All of my devices show up under Unknown room, though I do have rooms set up in the Lutron app.  I hardly use these room organizers anyway, as I barely ever use the Lutron app.

Thank you!

**Comment by FlyingDiver** [comment] 2022-06-22 23:58
You can change the room to make it easier to find in the future.  And add names that weren't in the Lutron app.

**Comment by FlyingDiver** [comment] 2022-07-10 18:58
2022.0.6 released

**Closed as completed by FlyingDiver** 2022-07-10 18:58 UTC
